/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  important: true,
  theme: {
    extend: {
      backgroundImage: {
        "gradient-to-t-custom":
          "linear-gradient(to top, var(--tw-gradient-from) 0%, white 53.94%, var(--tw-gradient-to) 151.64%)",
        // background: linear-gradient(180deg, #FFFFFF 53.94%, rgba(28, 101, 108, 0.495) 151.64%);
      },
      colors: {
        color: "#707070",
        bg: "#FFFFFF",
        primaryColorScheme: "gray",
        primary: "#00ADBC",
        secondary: "#FFA500",
        darkGray: "#5B6770",
        lightGrayBG: "#5B677014",
        gray: "#5B677014",
        gradientTop: "#FFFFFF",
        gradientBottom: "#FFFFFF",
        headingColor: "black",
        cardBg: "#FFFFFF",
        cardLink: "black",
        cardLinkHover: "#3182CE",
        black: "#201D1D",
        lightBG: "#5B677014",
        darkBG: "#5B6770",
        alt: "#1C656C",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-primary",
    "bg-secondary",
    "bg-lightGrayBG",
    "bg-darkGray",
    "bg-gradientTop",
    "bg-gradientBottom",
    "bg-headingColor",
    "bg-cardBg",
    "bg-gray",
    "bg-lightBG",
    "bg-darkBG",
    "bg-alt",
    "text-primary",
    "text-secondary",
    "text-darkGray",
    "text-headingColor",
    "text-cardLink",
    "text-cardLinkHover",
    "text-black",
    "text-alt",
    "border-primary",
    "border-secondary",
    "border-darkGray",
    "border-headingColor",
    "border-cardLink",
    "border-cardLinkHover",
    "border-black",
    "border-alt",
    "from-primary",
    "from-secondary",
    "from-darkGray",
    "from-headingColor",
    "from-cardLink",
    "from-cardLinkHover",
    "from-black",
    "from-alt",
    "to-primary",
    "to-secondary",
    "to-darkGray",
    "to-headingColor",
    "to-cardLink",
  ],
};
